swagger: "2.0"
info:
  version: "0.0.1"
  title: The Electronics Store App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /v1  
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/plain
securityDefinitions:
  UserSecurity:
    type: basic
security:
  - UserSecurity: [] 
paths:
  /employees:
    x-swagger-router-controller: employee
    get:
      description: Return all the employees
      operationId: getEmployees
      responses: 
        "200":
          description: Success get all the employees
          schema:
            type: array
            items:
              $ref: "#/definitions/Employee"
        "500":
          description: Unexpected Error
          schema:
            type: object
            properties:
              message:
                type: string
    post:
      description: Create one new Employee
      operationId: postEmployees
      parameters:
        - in: body
          name: body
          description: The employee to be added
          required: true
          schema:
            $ref: "#/definitions/Employee"
      responses:
        "204":
          description: Sucess
        "500":
          description: unexpected Error
          schema:
            type: object
            properties:
              message:
                type: string
      security:
        - UserSecurity: []
      
  /Employees/{EmployeeId}:
    x-swagger-router-controller: Employee
    parameters:
    - in: path
      name: EmployeeId
      type: integer
      required: true
      description: Numeric Id of the Employee
    delete:
      description: Remove a Employee
      operationId: deleteEmployee
      responses:
        "204":
          description: Success
        "404":
          description: The Id passed does not match any Employee.
        "500":
          description: unexpected Error
          schema:
            type: object
            properties:
                message:
                    type: string
    put:
      parameters:
      - in: body
        name: Employee
        schema:
          $ref: "#/definitions/Employee"
        required: true
        description: Id of the Employee you want to get the comments.
      description: updates a Employee
      operationId: putEmployees
      responses:
        "204":
          description: Success
        "404":
          description: The Id passed does not match any Employee.
        "500":
          description: unexpected Error
          schema:
            type: object
            properties:
                message:
                    type: string
  
  /Items:
    x-swagger-router-controller: item
    get:
      description: Return all the Items
      operationId: getItems
      responses: 
        "200":
          description: Success get all the Items
          schema:
            type: array
            items:
              $ref: "#/definitions/Item"
        "500":
          description: Unexpected Error
          schema:
            type: object
            properties:
              message:
                type: string
    post:
      description: Create one new Item
      operationId: postItems
      parameters:
        - in: body
          name: body
          description: The item to be added
          required: true
          schema:
            $ref: "#/definitions/Item"
      responses:
        "204":
          description: Sucess
        "500":
          description: unexpected Error
          schema:
            type: object
            properties:
              message:
                type: string
      
  /Items/{ItemId}:
    x-swagger-router-controller: Item
    parameters:
    - in: path
      name: ItemId
      type: integer
      required: true
      description: Numeric Id of the Item
    delete:
      description: Remove a Item
      operationId: deleteItem
      responses:
        "204":
          description: Success
        "404":
          description: The Id passed does not match any Item.
        "500":
          description: unexpected Error
          schema:
            type: object
            properties:
                message:
                    type: string
    put:
      parameters:
      - in: body
        name: Item
        schema:
          $ref: "#/definitions/Item"
        required: true
        description: Id of the Item you want to get the comments.
      description: updates a Item
      operationId: putItems
      responses:
        "204":
          description: Success
        "404":
          description: The Id passed does not match any Item.
        "500":
          description: unexpected Error
          schema:
            type: object
            properties:
                message:
                    type: string  


  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Employee:
    properties:
      id:
        type: integer
      name: 
        type: string
      password:
        type: string
  Item:
     properties:
      id:
        type: integer
      name: 
        type: string
      stock:
        type: integer
               


